#!/bin/bash

# Folder Structure Migration Script
# This script migrates 168 files based on planning/2. TODOs/mapFolderStructures.json
# Generated by Claude for issue #488

set -e  # Exit on any error

echo "========================================="
echo "Folder Structure Migration"
echo "========================================="
echo ""
echo "This script will move 168 files in 12 batches"
echo "Press Ctrl+C to cancel, or Enter to continue..."
read

# Color codes for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to execute a batch
execute_batch() {
    local batch_name="$1"
    echo ""
    echo -e "${BLUE}=========================================${NC}"
    echo -e "${BLUE}$batch_name${NC}"
    echo -e "${BLUE}=========================================${NC}"
}

# Function to move a file
move_file() {
    local current="$1"
    local new="$2"
    local new_dir=$(dirname "$new")

    # Create directory if it doesn't exist
    mkdir -p "$new_dir"

    # Move the file
    echo "  $current -> $new"
    git mv "$current" "$new"
}

# Batch 1: Core Infrastructure (5 files)
execute_batch "Batch 1: Core Infrastructure (5 files)"
mkdir -p src/core/auth/stores
mkdir -p src/core/firm/stores
move_file "src/core/stores/auth/authFirmSetup.js" "src/core/auth/stores/authFirmSetup.js"
move_file "src/core/stores/auth/authStateHandlers.js" "src/core/auth/stores/authStateHandlers.js"
move_file "src/core/stores/auth/authStore.js" "src/core/auth/stores/authStore.js"
move_file "src/core/stores/auth/index.js" "src/core/auth/stores/index.js"
move_file "src/core/stores/firm.js" "src/core/firm/stores/firm.js"
git status
echo -e "${GREEN}✓ Batch 1 complete${NC}"

# Batch 2: Authentication Feature (3 files)
execute_batch "Batch 2: Authentication Feature (3 files)"
mkdir -p src/features/authentication/components
mkdir -p src/features/authentication/services
mkdir -p src/features/authentication/guards
move_file "src/components/features/auth/LoginForm.vue" "src/features/authentication/components/LoginForm.vue"
move_file "src/services/authService.js" "src/features/authentication/services/authService.js"
move_file "src/router/guards/auth.js" "src/features/authentication/guards/authGuard.js"
git status
echo -e "${GREEN}✓ Batch 2 complete${NC}"

# Batch 3: Matters Feature (7 files)
execute_batch "Batch 3: Matters Feature (7 files)"
mkdir -p src/features/matters/composables
mkdir -p src/features/matters/services
mkdir -p src/features/matters/stores
mkdir -p src/features/matters/utils
mkdir -p src/features/matters/guards
mkdir -p src/features/matters/views
move_file "src/composables/useMatters.js" "src/features/matters/composables/useMatters.js"
move_file "src/services/matterService.js" "src/features/matters/services/matterService.js"
move_file "src/stores/matterView.js" "src/features/matters/stores/matterView.js"
move_file "src/utils/seedMatters.js" "src/features/matters/utils/seedMatters.js"
move_file "src/router/guards/matter.js" "src/features/matters/guards/matterGuard.js"
move_file "src/views/Matters.vue" "src/features/matters/views/Matters.vue"
move_file "src/views/MatterDetail.vue" "src/features/matters/views/MatterDetail.vue"
git status
echo -e "${GREEN}✓ Batch 3 complete${NC}"

# Batch 3b: More Matters views (2 files)
move_file "src/views/EditMatter.vue" "src/features/matters/views/EditMatter.vue"
move_file "src/views/NewMatter.vue" "src/features/matters/views/NewMatter.vue"
move_file "src/views/MatterImport.vue" "src/features/matters/views/MatterImport.vue"
echo -e "${GREEN}✓ Batch 3b complete${NC}"

# Batch 4: Profile Feature (5 files)
execute_batch "Batch 4: Profile Feature (5 files)"
mkdir -p src/features/profile/composables
mkdir -p src/features/profile/services
mkdir -p src/features/profile/stores
mkdir -p src/features/profile/views
move_file "src/composables/useFirmMembers.js" "src/features/profile/composables/useFirmMembers.js"
move_file "src/composables/useUsers.js" "src/features/profile/composables/useUsers.js"
move_file "src/services/profileService.js" "src/features/profile/services/profileService.js"
move_file "src/services/userService.js" "src/features/profile/services/userService.js"
move_file "src/core/stores/userPreferences.js" "src/features/profile/stores/userPreferences.js"
move_file "src/views/Profile.vue" "src/features/profile/views/Profile.vue"
move_file "src/views/Settings.vue" "src/features/profile/views/Settings.vue"
git status
echo -e "${GREEN}✓ Batch 4 complete${NC}"

# Batch 5: Upload Feature (1 file)
execute_batch "Batch 5: Upload Feature (1 file)"
mkdir -p src/features/upload/services
move_file "src/services/uploadService.js" "src/features/upload/services/uploadService.js"
git status
echo -e "${GREEN}✓ Batch 5 complete${NC}"

# Batch 6: Shared Components (9 files)
execute_batch "Batch 6: Shared Components (9 files)"
mkdir -p src/shared/components/layout
mkdir -p src/shared/components/navigation
mkdir -p src/shared/components/base
mkdir -p src/shared/components/home
mkdir -p src/shared/components/ui
move_file "src/components/layout/AppHeader.vue" "src/shared/components/layout/AppHeader.vue"
move_file "src/components/layout/AppSideBar.vue" "src/shared/components/layout/AppSideBar.vue"
move_file "src/components/AppSwitcher.vue" "src/shared/components/navigation/AppSwitcher.vue"
move_file "src/components/base/BaseSearchBar.vue" "src/shared/components/base/BaseSearchBar.vue"
move_file "src/components/base/HoldToConfirmButton.vue" "src/shared/components/base/HoldToConfirmButton.vue"
move_file "src/shared/components/ClearAllButton.vue" "src/shared/components/base/ClearAllButton.vue"
move_file "src/components/home/AddAppTab.vue" "src/shared/components/home/AddAppTab.vue"
move_file "src/components/home/FeaturesTab.vue" "src/shared/components/home/FeaturesTab.vue"
move_file "src/components/home/FirstAppTab.vue" "src/shared/components/home/FirstAppTab.vue"
move_file "src/components/home/LocalDevTab.vue" "src/shared/components/home/LocalDevTab.vue"
move_file "src/components/ui/SegmentedControl.vue" "src/shared/components/ui/SegmentedControl.vue"
git status
echo -e "${GREEN}✓ Batch 6 complete${NC}"

# Batch 7: Core Composables (3 files)
execute_batch "Batch 7: Core Composables (3 files)"
move_file "src/composables/useAsyncInspector.js" "src/core/composables/useAsyncInspector.js"
move_file "src/composables/useAsyncRegistry.js" "src/core/composables/useAsyncRegistry.js"
move_file "src/composables/useFavicon.js" "src/core/composables/useFavicon.js"
git status
echo -e "${GREEN}✓ Batch 7 complete${NC}"

# Batch 8: Documents - Table Components (10 files)
execute_batch "Batch 8: Documents - Table Components (10 files)"
mkdir -p src/features/documents/components/table
mkdir -p src/features/documents/components/table/cells
move_file "src/components/base/DocumentTable.vue" "src/features/documents/components/table/DocumentTable.vue"
move_file "src/components/base/DragHandle.vue" "src/features/documents/components/table/DragHandle.vue"
move_file "src/components/base/CellContentTooltip.vue" "src/features/documents/components/table/CellContentTooltip.vue"
move_file "src/components/base/DocumentPeekTooltip.vue" "src/features/documents/components/table/DocumentPeekTooltip.vue"
move_file "src/features/organizer/components/cells/BadgeCell.vue" "src/features/documents/components/table/cells/BadgeCell.vue"
move_file "src/features/organizer/components/cells/DateCell.vue" "src/features/documents/components/table/cells/DateCell.vue"
move_file "src/features/organizer/components/cells/FileSizeCell.vue" "src/features/documents/components/table/cells/FileSizeCell.vue"
move_file "src/features/organizer/components/cells/TagListCell.vue" "src/features/documents/components/table/cells/TagListCell.vue"
move_file "src/features/organizer/components/cells/TextCell.vue" "src/features/documents/components/table/cells/TextCell.vue"
git status
echo -e "${GREEN}✓ Batch 8 complete${NC}"

# Batch 9: Documents - Viewer & AI Components (12 files)
execute_batch "Batch 9: Documents - Viewer & AI Components (12 files)"
mkdir -p src/features/documents/components/viewer
mkdir -p src/features/documents/components/ai-analysis
mkdir -p src/features/documents/components/tags/composables
move_file "src/components/document/DocumentNavigationBar.vue" "src/features/documents/components/viewer/DocumentNavigationBar.vue"
move_file "src/components/document/DocumentMetadataPanel.vue" "src/features/documents/components/viewer/DocumentMetadataPanel.vue"
move_file "src/components/document/PdfViewerArea.vue" "src/features/documents/components/viewer/PdfViewerArea.vue"
move_file "src/components/document/PdfThumbnailPanel.vue" "src/features/documents/components/viewer/PdfThumbnailPanel.vue"
move_file "src/components/document/tabs/AIAnalysisTab.vue" "src/features/documents/components/ai-analysis/AIAnalysisTab.vue"
move_file "src/components/document/tabs/DigitalFileTab.vue" "src/features/documents/components/ai-analysis/DigitalFileTab.vue"
move_file "src/components/document/tabs/DocumentTab.vue" "src/features/documents/components/ai-analysis/DocumentTab.vue"
move_file "src/components/document/tabs/ReviewTab.vue" "src/features/documents/components/ai-analysis/ReviewTab.vue"
move_file "src/components/document/tabs/ai-analysis/AIAnalysisButton.vue" "src/features/documents/components/ai-analysis/AIAnalysisButton.vue"
move_file "src/components/document/tabs/ai-analysis/AIAnalysisError.vue" "src/features/documents/components/ai-analysis/AIAnalysisError.vue"
move_file "src/components/document/tabs/ai-analysis/AIAnalysisFieldItem.vue" "src/features/documents/components/ai-analysis/AIAnalysisFieldItem.vue"
move_file "src/components/document/tabs/ai-analysis/AIReviewFieldItem.vue" "src/features/documents/components/ai-analysis/AIReviewFieldItem.vue"
move_file "src/components/features/tags/EditableTag.vue" "src/features/documents/components/tags/EditableTag.vue"
move_file "src/components/features/tags/composables/useTagEditing.js" "src/features/documents/components/tags/composables/useTagEditing.js"
git status
echo -e "${GREEN}✓ Batch 9 complete${NC}"

# Batch 10: Documents - Organizer Components (15 files)
execute_batch "Batch 10: Documents - Organizer Components (15 files)"
move_file "src/features/organizer/components/AITagChip.vue" "src/features/documents/components/AITagChip.vue"
move_file "src/features/organizer/components/ColumnSelector.vue" "src/features/documents/components/ColumnSelector.vue"
move_file "src/features/organizer/components/FileDetails.vue" "src/features/documents/components/FileDetails.vue"
move_file "src/features/organizer/components/FileGrid.vue" "src/features/documents/components/FileGrid.vue"
move_file "src/features/organizer/components/FileItem.vue" "src/features/documents/components/FileItem.vue"
move_file "src/features/organizer/components/FilePreview.vue" "src/features/documents/components/FilePreview.vue"
move_file "src/features/organizer/components/FileSearch.vue" "src/features/documents/components/FileSearch.vue"
move_file "src/features/organizer/components/FileTypeFilters.vue" "src/features/documents/components/FileTypeFilters.vue"
move_file "src/features/organizer/components/FolderBreadcrumbs.vue" "src/features/documents/components/FolderBreadcrumbs.vue"
move_file "src/features/organizer/components/FolderHierarchySelector.vue" "src/features/documents/components/FolderHierarchySelector.vue"
move_file "src/features/organizer/components/PdfPageCanvas.vue" "src/features/documents/components/PdfPageCanvas.vue"
move_file "src/features/organizer/components/PdfThumbnailList.vue" "src/features/documents/components/PdfThumbnailList.vue"
move_file "src/features/organizer/components/TagOptionsManager.vue" "src/features/documents/components/TagOptionsManager.vue"
move_file "src/features/organizer/components/ViewModeToggle.vue" "src/features/documents/components/ViewModeToggle.vue"
git status
echo -e "${GREEN}✓ Batch 10 complete${NC}"

# Batch 11: Documents - Composables (38 files)
execute_batch "Batch 11: Documents - Composables (38 files)"
mkdir -p src/features/documents/composables
move_file "src/composables/useAIAnalysis.js" "src/features/documents/composables/useAIAnalysis.js"
move_file "src/composables/useCellTooltip.js" "src/features/documents/composables/useCellTooltip.js"
move_file "src/composables/useColumnDragDrop.js" "src/features/documents/composables/useColumnDragDrop.js"
move_file "src/composables/useColumnResize.js" "src/features/documents/composables/useColumnResize.js"
move_file "src/composables/useColumnSort.js" "src/features/documents/composables/useColumnSort.js"
move_file "src/composables/useColumnVisibility.js" "src/features/documents/composables/useColumnVisibility.js"
move_file "src/composables/useDocumentPeek.js" "src/features/documents/composables/useDocumentPeek.js"
move_file "src/composables/useDocumentTablePeek.js" "src/features/documents/composables/useDocumentTablePeek.js"
move_file "src/composables/useTooltipTiming.js" "src/features/documents/composables/useTooltipTiming.js"
move_file "src/composables/useVirtualTable.js" "src/features/documents/composables/useVirtualTable.js"
move_file "src/features/organizer/composables/useCanvasPreloader.js" "src/features/documents/composables/useCanvasPreloader.js"
move_file "src/features/organizer/composables/useCategoryEditActions.js" "src/features/documents/composables/useCategoryEditActions.js"
move_file "src/features/organizer/composables/useCategoryEditForm.js" "src/features/documents/composables/useCategoryEditForm.js"
move_file "src/features/organizer/composables/useCategoryEditState.js" "src/features/documents/composables/useCategoryEditState.js"
move_file "src/features/organizer/composables/useCategoryEditValidation.js" "src/features/documents/composables/useCategoryEditValidation.js"
move_file "src/features/organizer/composables/useCategoryFormHelpers.js" "src/features/documents/composables/useCategoryFormHelpers.js"
move_file "src/features/organizer/composables/useCategoryManager.js" "src/features/documents/composables/useCategoryManager.js"
move_file "src/features/organizer/composables/useCategoryTypeConversion.js" "src/features/documents/composables/useCategoryTypeConversion.js"
move_file "src/features/organizer/composables/useDocumentNavigation.js" "src/features/documents/composables/useDocumentNavigation.js"
move_file "src/features/organizer/composables/useDocumentPreloader.js" "src/features/documents/composables/useDocumentPreloader.js"
move_file "src/features/organizer/composables/useEvidenceDeduplication.js" "src/features/documents/composables/useEvidenceDeduplication.js"
move_file "src/features/organizer/composables/useEvidenceLoader.js" "src/features/documents/composables/useEvidenceLoader.js"
move_file "src/features/organizer/composables/useFilePreview.js" "src/features/documents/composables/useFilePreview.js"
move_file "src/features/organizer/composables/useFileSearch.js" "src/features/documents/composables/useFileSearch.js"
move_file "src/features/organizer/composables/useFileViewer.js" "src/features/documents/composables/useFileViewer.js"
move_file "src/features/organizer/composables/useNavigationPerformanceTracker.js" "src/features/documents/composables/useNavigationPerformanceTracker.js"
move_file "src/features/organizer/composables/usePageComplexity.js" "src/features/documents/composables/usePageComplexity.js"
move_file "src/features/organizer/composables/usePagePreloader.js" "src/features/documents/composables/usePagePreloader.js"
move_file "src/features/organizer/composables/usePageVisibility.js" "src/features/documents/composables/usePageVisibility.js"
move_file "src/features/organizer/composables/usePdfCache.js" "src/features/documents/composables/usePdfCache.js"
move_file "src/features/organizer/composables/usePdfMetadata.js" "src/features/documents/composables/usePdfMetadata.js"
move_file "src/features/organizer/composables/usePdfViewer.js" "src/features/documents/composables/usePdfViewer.js"
move_file "src/features/organizer/composables/useRenderTracking.js" "src/features/documents/composables/useRenderTracking.js"
move_file "src/features/organizer/composables/useTagColor.js" "src/features/documents/composables/useTagColor.js"
move_file "src/features/organizer/composables/useThumbnailRenderer.js" "src/features/documents/composables/useThumbnailRenderer.js"
move_file "src/features/organizer/composables/useViewerNavigation.js" "src/features/documents/composables/useViewerNavigation.js"
git status
echo -e "${GREEN}✓ Batch 11 complete${NC}"

# Batch 12: Documents - Services (14 files)
execute_batch "Batch 12: Documents - Services (14 files)"
mkdir -p src/features/documents/services
move_file "src/services/aiMetadataExtractionService.js" "src/features/documents/services/aiMetadataExtractionService.js"
move_file "src/services/fileService.js" "src/features/documents/services/fileService.js"
move_file "src/features/organizer/services/aiProcessingService.js" "src/features/documents/services/aiProcessingService.js"
move_file "src/features/organizer/services/aiTagService.js" "src/features/documents/services/aiTagService.js"
move_file "src/features/organizer/services/categoryService.js" "src/features/documents/services/categoryService.js"
move_file "src/features/organizer/services/evidenceDocumentService.js" "src/features/documents/services/evidenceDocumentService.js"
move_file "src/features/organizer/services/evidenceQueryService.js" "src/features/documents/services/evidenceQueryService.js"
move_file "src/features/organizer/services/evidenceService.js" "src/features/documents/services/evidenceService.js"
move_file "src/features/organizer/services/fileProcessingService.js" "src/features/documents/services/fileProcessingService.js"
move_file "src/features/organizer/services/index.js" "src/features/documents/services/index.js"
move_file "src/features/organizer/services/systemCategoriesService.js" "src/features/documents/services/systemCategoriesService.js"
move_file "src/features/organizer/services/systemCategoryService.js" "src/features/documents/services/systemCategoryService.js"
move_file "src/features/organizer/services/tagOperationService.js" "src/features/documents/services/tagOperationService.js"
move_file "src/features/organizer/services/tagSubcollectionService.js" "src/features/documents/services/tagSubcollectionService.js"
git status
echo -e "${GREEN}✓ Batch 12 complete${NC}"

# Batch 13: Documents - Stores (9 files)
execute_batch "Batch 13: Documents - Stores (9 files)"
mkdir -p src/features/documents/stores
move_file "src/stores/documentView.js" "src/features/documents/stores/documentView.js"
move_file "src/features/organizer/stores/categoryComposables.js" "src/features/documents/stores/categoryComposables.js"
move_file "src/features/organizer/stores/categoryCore.js" "src/features/documents/stores/categoryCore.js"
move_file "src/features/organizer/stores/categoryStore.js" "src/features/documents/stores/categoryStore.js"
move_file "src/features/organizer/stores/categoryValidation.js" "src/features/documents/stores/categoryValidation.js"
move_file "src/features/organizer/stores/organizer.js" "src/features/documents/stores/organizer.js"
move_file "src/features/organizer/stores/organizerCore.js" "src/features/documents/stores/organizerCore.js"
move_file "src/features/organizer/stores/organizerQueryStore.js" "src/features/documents/stores/organizerQueryStore.js"
move_file "src/features/organizer/stores/virtualFolderStore.js" "src/features/documents/stores/virtualFolderStore.js"
git status
echo -e "${GREEN}✓ Batch 13 complete${NC}"

# Batch 14: Documents - Utils/Constants/Views (15 files)
execute_batch "Batch 14: Documents - Utils/Constants/Views (15 files)"
mkdir -p src/features/documents/utils
mkdir -p src/features/documents/constants
mkdir -p src/features/documents/types
mkdir -p src/features/documents/views
move_file "src/utils/categoryFieldMapping.js" "src/features/documents/utils/categoryFieldMapping.js"
move_file "src/features/organizer/utils/automaticTagColors.js" "src/features/documents/utils/automaticTagColors.js"
move_file "src/features/organizer/utils/categoryFormHelpers.js" "src/features/documents/utils/categoryFormHelpers.js"
move_file "src/features/organizer/utils/categoryFormOptions.js" "src/features/documents/utils/categoryFormOptions.js"
move_file "src/features/organizer/utils/categoryIdGenerator.js" "src/features/documents/utils/categoryIdGenerator.js"
move_file "src/features/organizer/utils/categoryTypeConversions.js" "src/features/documents/utils/categoryTypeConversions.js"
move_file "src/features/organizer/utils/categoryTypes.js" "src/features/documents/utils/categoryTypes.js"
move_file "src/features/organizer/utils/currencyOptions.js" "src/features/documents/utils/currencyOptions.js"
move_file "src/features/organizer/utils/fileUtils.js" "src/features/documents/utils/fileUtils.js"
move_file "src/features/organizer/utils/fileViewerUtils.js" "src/features/documents/utils/fileViewerUtils.js"
move_file "src/features/organizer/utils/previewGenerators.js" "src/features/documents/utils/previewGenerators.js"
move_file "src/features/organizer/utils/uploadUtils.js" "src/features/documents/utils/uploadUtils.js"
move_file "src/features/organizer/utils/uploadViewerUtils.js" "src/features/documents/utils/uploadViewerUtils.js"
move_file "src/features/organizer/constants/systemCategories.js" "src/features/documents/constants/systemCategories.js"
move_file "src/features/organizer/types/viewer.types.js" "src/features/documents/types/viewer.types.js"
git status
echo -e "${GREEN}✓ Batch 14 complete${NC}"

# Batch 15: Documents - Views (7 files)
execute_batch "Batch 15: Documents - Views (7 files)"
move_file "src/views/Documents.vue" "src/features/documents/views/Documents.vue"
move_file "src/views/Analyze.vue" "src/features/documents/views/Analyze.vue"
move_file "src/features/organizer/views/CategoryCreationWizard.vue" "src/features/documents/views/CategoryCreationWizard.vue"
move_file "src/features/organizer/views/CategoryEditWizard.vue" "src/features/documents/views/CategoryEditWizard.vue"
move_file "src/features/organizer/views/CategoryManager.vue" "src/features/documents/views/CategoryManager.vue"
move_file "src/features/organizer/views/FileViewer.vue" "src/features/documents/views/FileViewer.vue"
move_file "src/features/organizer/views/ViewDocument.vue" "src/features/documents/views/ViewDocument.vue"
git status
echo -e "${GREEN}✓ Batch 15 complete${NC}"

echo ""
echo -e "${GREEN}=========================================${NC}"
echo -e "${GREEN}Migration Complete!${NC}"
echo -e "${GREEN}=========================================${NC}"
echo ""
echo "All 168 files have been moved successfully."
echo ""
echo "Next steps:"
echo "1. Update all import statements across the codebase"
echo "2. Run 'npm run build' to verify everything works"
echo "3. Run 'npm run test:run' to verify tests pass"
echo "4. Commit the changes with: git commit -m 'Complete folder structure migration'"
echo ""
echo "Note: Import updates will need to be done separately."
echo "Consider using a search-and-replace tool or script for import path updates."
