name: Claude Task
description: Create a task specifically for the Claude Night Shift workflow.
title: "[Claude] "
labels: ["status: ready-for-ai"]
assignees: 
  - Listbot.ca # Automatically assigns the issue to the Listbot.ca app for processing

body:
  - type: markdown
    attributes:
      value: |
        Thanks for creating a task for Claude! This issue has been automatically labeled and assigned to ensure it is picked up by the Night Shift workflow.
  
  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: What specifically do you want Claude to do? Be as detailed as possible and clearly define the goal.
      placeholder: "Please refactor the login function to use async/await across all relevant files, following TypeScript best practices..."
    validations:
      required: true

  - type: input
    id: files
    attributes:
      label: Relevant Files (Optional but Recommended)
      description: Guide Claude to the right place. List file paths relevant to the task (e.g., src/auth/login.ts).
      placeholder: src/components/Header.tsx, utils/api.ts
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context and Constraints
      description: Provide any constraints, library requirements, or specific design patterns Claude must follow.