import { computed } from 'vue';
import { generateRegexExamples, isRegexDefinitionValid } from '../utils/categoryFormHelpers.js';

/**
 * Composable for category form helper utilities
 * Handles regex validation and example generation
 *
 * @param {Object} editedCategory - Reactive reference to the edited category
 * @param {Object} route - Vue Router route object
 * @returns {Object} Helper utilities for the category form
 */
export function useCategoryFormHelpers(editedCategory, route) {
  // Computed property to auto-generate regex examples
  const autoGeneratedExamples = computed(() => {
    if (editedCategory.value.type !== 'Regex') {
      return [];
    }
    return generateRegexExamples(editedCategory.value.regexDefinition);
  });

  // Computed property to check if regex is valid
  const isRegexValid = computed(() => {
    // If not a Regex type, always valid
    if (editedCategory.value.type !== 'Regex') {
      return true;
    }
    // Check if regex is valid based on generated examples
    return isRegexDefinitionValid(editedCategory.value.regexDefinition, autoGeneratedExamples.value);
  });

  // Computed property to check if current category is a system category
  const isSystemCategoryComputed = computed(() => {
    return route.query.source === 'system';
  });

  return {
    autoGeneratedExamples,
    isRegexValid,
    isSystemCategoryComputed,
  };
}
