import { computed } from 'vue';
import { generateRegexExamples, isRegexDefinitionValid } from '../utils/categoryFormHelpers.js';

/**
 * Composable for category form helper utilities
 * @param {Object} params - Configuration parameters
 * @param {Ref} params.categorySource - Source of the category (system/firm/matter)
 * @param {Ref} params.editedCategory - Edited category data
 * @returns {Object} Helper computed properties
 */
export function useCategoryFormHelpers({ categorySource, editedCategory }) {
  /**
   * Computed property to auto-generate regex examples
   */
  const autoGeneratedExamples = computed(() => {
    if (editedCategory.value.type !== 'Regex') {
      return [];
    }
    return generateRegexExamples(editedCategory.value.regexDefinition);
  });

  /**
   * Computed property to check if regex is valid
   */
  const isRegexValid = computed(() => {
    // If not a Regex type, always valid
    if (editedCategory.value.type !== 'Regex') {
      return true;
    }
    // Check if regex is valid based on generated examples
    return isRegexDefinitionValid(editedCategory.value.regexDefinition, autoGeneratedExamples.value);
  });

  /**
   * Computed property to check if current category is a system category
   */
  const isSystemCategoryComputed = computed(() => {
    return categorySource.value === 'system';
  });

  return {
    // Computed
    autoGeneratedExamples,
    isRegexValid,
    isSystemCategoryComputed,
  };
}
